# Spring Cloud Gateway를 사용하여 API Gateway를 구성하는 설정 파일
# Spring Gateway 서비스는 Netty라는 비동기 서비스가 작동이된다.
# 실행 순서
# Gateway Handler Mapping -> Predicate -> PreFilter -> 서비스 실행 -> PostFilter -> Gateway Handler Mapping

server:
  # API Gateway가 바인딩 될 포트 지정
  port: 8000

eureka:
  # Eureka 클라이언트 구성
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # Eureka Server의 위치를 지정
      defaultZone: http://localhost:8761/eureka

spring:
  # API Gateway 서비스 이름 지정
  application:
    name: apigateway-service
  # RabbitMQ를 사용하여 메시지를 전송하는 데 사용되는 구성
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      # 모든 라우팅에 적용되는 필터(Global 필터)
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            # 요청 전과 후에 로그를 출력하는지 여부
            preLogger: true
            postLogger: true
      # 라우트 정의
      routes:
#        - id: user-service
#            uri: lb://USER-SERVICE
#            predicates:
#              - Path=/user-service/**
        # 라우터의 이름
        - id: user-service
          # 요청 정보를 어디에 포워딩 시켜줄 것인지 위치 정보
          # Discovery(Eureka Server) 서비스에 등록되어있는 MicroService 중에서
          # user-service(어플리케이션 이름)로 포워딩 시킬 것.
          uri: lb://USER-SERVICE
          # 요청을 분류하기 위한 조건 지정
          predicates:
            # client가 POST /user-service/login를 요청하면 uri 위치로 포워딩
            # login과 관련된 것은 Spring Security가 제공해주는 api
            - Path=/user-service/login
            - Method=POST
          # 요청에 대해 수행할 필터들을 지정
          filters:
            # Cookie 헤더를 제거 / Response Body에 어떤 정보도 남기지 않고, 새로운 Request Header로 요청
            - RemoveRequestHeader=Cookie
            # 사용자가 요청한 /user-service 제거 후 user micro service 에 전달
            # 실제 구현된 정보를 노출하지 않을 수 있음
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            # 로그인, 회원가입을 제외한 API들은 JWT를 통한 사용자 인증이 필요
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**

# JWT 토큰에 사용되는 비밀키 지정

token:
#  secret: user_token

# Actuator의 엔드포인트를 노출할지 여부를 지정
# busrefresh: 서비스의 설정을 다시 로드할 수 있는 엔드포인트
# health: 서비스의 상태를 나타내는 엔드포인트
# httptrace: HTTP 요청 흐름을 추적하는 엔드포인트
management:
  endpoint:
    web:
      exposure:
        # httptrace: 클라이언트 요청이 들어와서 스프링부트에 구성되어있는 마이크로서비스의 상태 확인
        include: refresh, health, beans, httptrace, busrefresh
